<a href="https://colab.research.google.com/github/MaxVieiraSantiago/Machine-Learning-Algorithms/blob/master/Linear%20Regression/Regress%C3%A3o_Vetorial_Suporte.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Regressão Support Vector Machine - SVM**

In [1]:
import numpy as np
import pandas as pd

### **Importação do Dataset Iris**

In [2]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [3]:
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

In [4]:
iris = pd.read_csv(url, names=colnames)

In [5]:
iris.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [6]:
iris.shape

(150, 5)

#### **Separação dos Atriutos**

In [7]:
X = iris.drop('Class', axis=1)
y = iris['Class']

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)

#### **Modelo de Regressão Vetorial de Suporte ( Kernel = Linear )**

In [15]:
from sklearn.svm import SVC
svcClassifier = SVC(kernel='linear')
svcClassifier.fit(X_train, y_train);

In [16]:
y_pred = svcClassifier.predict(X_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print( classification_report(y_test, y_pred) )

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1.00      0.94      0.97        18
 Iris-virginica       0.92      1.00      0.96        11

       accuracy                           0.98        45
      macro avg       0.97      0.98      0.98        45
   weighted avg       0.98      0.98      0.98        45



#### **Modelo de Regressão Vetorial de Suporte ( Kernel = Sigmóide )**

In [18]:
from sklearn.svm import SVC
svcClassifier = SVC(kernel="sigmoid")
svcClassifier.fit(X_train, y_train);

In [19]:
y_pred = svcClassifier.predict(X_test)

In [20]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))

[[ 0  0 16]
 [ 0  0 18]
 [ 0  0 11]]


#### **Modelo de Regressão Vetorial de Suporte ( Kernel = Polinomial )**

In [21]:
from sklearn.svm import SVC
svcClassifier = SVC(kernel='poly', degree=2)
svcClassifier.fit(X_train, y_train);

In [22]:
y_pred = svcClassifier.predict(X_test)

In [23]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]


#### **Modelo de Regressão Vetorial de Suporte ( Kernel = Gaussiana (rbf) )**

In [26]:
from sklearn.svm import SVC
svcClassifier = SVC(kernel='rbf')
svcClassifier.fit(X_train, y_train);